'use client';
import { useEffect, useState, useRef } from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import PlumbingScene from '@/components/plumbing-scene';
import ValleyMap from '@/components/valley-map';
import type { ModelKind } from '@/lib/plumbing-models';
import { categories, services, areas, reviews } from '@/lib/lpz-data';
export function SiteEffects(){const [bar,setBar]=useState(false);const [intro,setIntro]=useState(false);const cursor=useRef<HTMLDivElement>(null);useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let timer:ReturnType<typeof setTimeout>;if(!reduced&&innerWidth>800&&!sessionStorage.getItem('lpz-intro')){setIntro(true);sessionStorage.setItem('lpz-intro','seen');timer=setTimeout(()=>setIntro(false),2000)}const onScroll=()=>{const footer=document.querySelector('footer');setBar(scrollY>200&&(!footer||footer.getBoundingClientRect().top>innerHeight));const hero=document.querySelector<HTMLElement>('.hero-art');if(hero&&!reduced&&innerWidth>800)hero.style.transform=`translateY(${Math.min(scrollY*.14,100)}px) scale(1.04)`;};const onMove=(e:MouseEvent)=>{if(cursor.current){cursor.current.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;cursor.current.classList.toggle('on-link',!!(e.target as Element).closest('a,button,summary'))}};const close=(e:KeyboardEvent)=>{if(e.key==='Escape')document.querySelectorAll('header details[open]').forEach(x=>x.removeAttribute('open'))};addEventListener('scroll',onScroll,{passive:true});addEventListener('mousemove',onMove,{passive:true});addEventListener('keydown',close);onScroll();return()=>{clearTimeout(timer);removeEventListener('scroll',onScroll);removeEventListener('mousemove',onMove);removeEventListener('keydown',close)}},[]);return <>{intro&&<div className="cinematic-intro" aria-hidden="true"><img src="/assets/plumbing-hero.webp" alt=""/><div className="intro-light"/><div className="intro-ripple"/><img className="intro-logo" src="/assets/lpz-logo-web.png" alt=""/></div>}<div className="precision-cursor" ref={cursor} aria-hidden="true"/><div className={'mobile-actions '+(bar?'visible':'')} aria-hidden={!bar}><a tabIndex={bar?0:-1} href="tel:+16027768749">CALL LPZ</a><a tabIndex={bar?0:-1} href="/schedule-service/">SCHEDULE </a></div></>}
export function ServicePipeline(){const [active,setActive]=useState('0');return <Tabs value={active} onValueChange={setActive} className="pipeline-tabs"><TabsList className="pipeline-nav">{categories.map((c,i)=><TabsTrigger className="pipeline-trigger" value={String(i)} key={c.slug}><span className="pipe-node"/>{c.name}</TabsTrigger>)}</TabsList>{categories.map((c,i)=><TabsContent value={String(i)} key={c.slug} className="pipeline-panel"><div className="service-model"><PlumbingScene kind={(["construction","remodel","emergency","diagnostics","specialty"] as ModelKind[])[i]} scan={i===3}/></div><div className="pipeline-copy"><h3>{c.title}</h3><p>{c.intro}</p><div className="pipeline-services">{services.filter(s=>s.category===i).map(s=><a href={'/services/'+s.slug+'/'} key={s.slug}>{s.name} </a>)}</div><a className="text-link" href={'/services/'+c.slug+'/'}>Explore {c.name.toLowerCase()} </a></div></TabsContent>)}</Tabs>}
export function AreaMap(){return <ValleyMap/>}
const reviewTopics = ['Clear explanations', 'Thoughtful options', 'Responsive service', 'Attention to detail'];
export function ReviewExperience(){
  const [active,setActive]=useState('0');
  return <section className="section reviews" aria-label="Customer testimonials">
    <div className="reviews-heading"><div><p className="eyebrow">THE LPZ EXPERIENCE</p><h2>Care that comes<br/>through in the details.</h2></div><p>Clear communication. Considered solutions. Read what customers have shared about working with LPZ.</p></div>
    <Tabs value={active} onValueChange={setActive} orientation="vertical" className="review-layout">
      <TabsList className="review-tabs" aria-label="Choose a customer testimonial">
        {reviews.map((review,i)=><TabsTrigger className="review-tab" value={String(i)} key={review.name}><span className="review-avatar" aria-hidden="true">{review.name.split(' ').map(n=>n[0]).join('')}</span><span><strong>{review.name}</strong><small>{reviewTopics[i]}</small></span><span className="review-indicator" aria-hidden="true"/></TabsTrigger>)}
      </TabsList>
      {reviews.map((review,i)=><TabsContent key={review.name} value={String(i)} className="review-panel"><div className="review-panel-top"><span>CLIENT PERSPECTIVE</span><span>0{i+1} / 0{reviews.length}</span></div><figure><blockquote>“{review.quote}”</blockquote><figcaption><span className="review-signature" aria-hidden="true"/><div><strong>{review.name}</strong><span>LPZ Plumbing Solutions customer</span></div></figcaption></figure><p className="review-source">Customer testimonial published on <a href="https://lpzplumbing.com/">LPZ’s website</a>.</p></TabsContent>)}
    </Tabs>
  </section>
}
export function DiagnosticVisual(){const [scan,setScan]=useState(false);return <section className="section diagnostic diagnostic-3d"><div><p className="eyebrow">LESS GUESSWORK. MORE CLARITY.</p><h2>Know what’s<br/>below the surface.</h2><p>See inside a pipe with a camera inspection. Explore the model, then reveal the cutaway to follow the camera toward a potential obstruction.</p><a className="text-link" href="/services/plumbing-diagnostics/">Explore advanced diagnostics</a></div><div className="inspection-experience"><PlumbingScene kind="diagnostics" scan={scan} large/><div className="inspection-controls"><div><p className="eyebrow">{scan?'CUTAWAY / CAMERA VIEW':'EXTERIOR / PIPE ASSEMBLY'}</p><p>{scan?'The shell fades to reveal the camera, inspection light and a root intrusion.':'Rotate the model to explore. Reveal the cutaway to look inside.'}</p></div><button className="button scan-control-3d" onClick={()=>setScan(!scan)} aria-pressed={scan}>{scan?'Close cutaway':'Reveal inspection'}</button></div><p className="inspection-note">Interactive illustration. Actual pipe conditions and inspection access vary.</p></div></section>}

