import PlumbingScene from '@/components/plumbing-scene';
import type {ModelKind} from '@/lib/plumbing-models';
import { categories, services, areas } from '@/lib/lpz-data';
import type { Metadata } from 'next';
export const origin=process.env.NEXT_PUBLIC_SITE_URL||'https://lpzplumbing.com';
export function metadataFor(title:string,description:string,path:string):Metadata{return {title:title+' | LPZ Plumbing Solutions',description,alternates:{canonical:origin+path},openGraph:{title,description,url:origin+path,type:'website',siteName:'LPZ Plumbing Solutions'},twitter:{card:'summary',title,description}}}
export const business={'@context':'https://schema.org','@type':'Plumber','@id':origin+'/#business',name:'LPZ Plumbing Solutions',url:origin,telephone:'+16027768749',email:'lpzplumbing1@gmail.com',address:{'@type':'PostalAddress',streetAddress:'3919 Carver Road',addressLocality:'Laveen',addressRegion:'AZ',postalCode:'85339',addressCountry:'US'},openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],opens:'00:00',closes:'23:59'}],areaServed:areas.map(a=>({'@type':'City',name:a.name+', Arizona'})),identifier:'ROC-356849',sameAs:['https://www.instagram.com/lpzplumbingsolutions/','https://www.bbb.org/us/az/laveen/profile/plumber/lpz-plumbing-solutions-llc-1126-1000141703/']};
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>}
export function Breadcrumbs({items}:{items:{name:string,path:string}[]}){const all=[{name:'Home',path:'/'},...items];return <><nav className="breadcrumbs" aria-label="Breadcrumb">{all.map((a,i)=><span key={a.path}>{i>0&&' / '}{i===all.length-1?<span aria-current="page">{a.name}</span>:<a href={a.path}>{a.name}</a>}</span>)}</nav><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:all.map((a,i)=>({'@type':'ListItem',position:i+1,name:a.name,item:origin+a.path}))}}/></>}
export function FAQ({items}:{items:[string,string][]}){return <div className="faq">{items.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>}
export function ServiceDiagram({service}:{service:typeof services[number]}){return <figure className="service-schematic service-schematic-3d"><PlumbingScene kind={(['construction','remodel','emergency','diagnostics','specialty'] as ModelKind[])[service.category]} scan={service.category===3}/><figcaption>{service.name.toUpperCase()}</figcaption></figure>}

