'use client';
import { useEffect,useRef,useState } from 'react';
import type { ModelKind } from '@/lib/plumbing-models';
const names={construction:'New construction rough-in',remodel:'Bathroom fixture renovation',emergency:'Pipe leak and shutoff valve',diagnostics:'Sewer inspection camera',specialty:'Water filtration system'};
export default function PlumbingScene({kind,scan=false,large=false}:{kind:ModelKind;scan?:boolean;large?:boolean}){
 const host=useRef<HTMLDivElement>(null);const active=useRef(scan);const [ready,setReady]=useState(false);const [failed,setFailed]=useState(false);useEffect(()=>{active.current=scan},[scan]);
 useEffect(()=>{const el=host.current;if(!el)return;let cancelled=false;let dispose=()=>{};let visible=false;let started=false;const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible&&!started){started=true;void boot()}},{rootMargin:'150px'});observer.observe(el);
 async function boot(){try{const [THREE,{OrbitControls},{RoomEnvironment},{createPlumbingModel}]=await Promise.all([import('three'),import('three/addons/controls/OrbitControls.js'),import('three/addons/environments/RoomEnvironment.js'),import('@/lib/plumbing-models')]);if(cancelled)return;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0x071521,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el!.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label',names[kind]+' interactive 3D model. Drag to rotate.');renderer.domElement.setAttribute('role','img');
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(36,1,.1,50);camera.position.set(kind==='diagnostics'?5.5:4.4,kind==='diagnostics'?3:3.3,kind==='diagnostics'?6.6:5.8);const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();const environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;room.dispose();pmrem.dispose();
 const model=createPlumbingModel(kind);scene.add(model.root);const fill=new THREE.HemisphereLight(0xdbefff,0x102838,2.1);scene.add(fill);const key=new THREE.DirectionalLight(0xe4f4ff,3);key.position.set(-3,6,5);scene.add(key);const rim=new THREE.PointLight(0x008fff,18,20);rim.position.set(3,2,-3);scene.add(rim);
 const floor=new THREE.Mesh(new THREE.CircleGeometry(5,64),new THREE.MeshStandardMaterial({color:0x0b1c28,roughness:.5,metalness:.4,transparent:true,opacity:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.2;scene.add(floor);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableZoom=false;controls.enablePan=false;controls.enableDamping=!reduced;controls.dampingFactor=.07;controls.minPolarAngle=.3;controls.maxPolarAngle=Math.PI*.65;controls.autoRotate=!reduced;controls.autoRotateSpeed=.25;controls.target.set(0,-.02,0);controls.update();
 let frame=0,last=0,progress=scan?1:0;const resize=new ResizeObserver(()=>{const w=el!.clientWidth,h=el!.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(el!);const animate=(time:number)=>{frame=requestAnimationFrame(animate);if(!visible||document.hidden||time-last<33)return;last=time;const goal=active.current?1:0;progress=reduced?goal:progress+(goal-progress)*.06;model.update(reduced?0:time/1000,progress);controls.autoRotate=!reduced&&!active.current;controls.update();renderer.render(scene,camera)};frame=requestAnimationFrame(animate);setReady(true);
 dispose=()=>{cancelAnimationFrame(frame);resize.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});environment.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()};
 }catch{if(!cancelled)setFailed(true)}}
 return()=>{cancelled=true;observer.disconnect();dispose()};
 },[kind]);
 return <div className={'model-stage '+(large?'model-stage-large ':'')+(ready?'model-ready':'')}><div className="model-canvas" ref={host}/><div className="model-topline"><span>{kind==='diagnostics'&&scan?'INSPECTION ACTIVE':'INTERACTIVE 3D'}</span><span className="model-status"/></div>{!ready&&<div className="model-loading">{failed?names[kind]:'Preparing '+names[kind].toLowerCase()+'…'}</div>}<div className="model-caption"><span>{names[kind]}</span><span>DRAG TO ROTATE</span></div></div>
}

