'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Leaflet from 'leaflet';
import type {FeatureCollection,Feature,Geometry} from 'geojson';
import {areas} from '@/lib/lpz-data';
import 'leaflet/dist/leaflet.css';
type Props={NAME?:string;BASENAME?:string;GEOID?:string};
export default function ValleyMap(){const host=useRef<HTMLDivElement>(null);const controller=useRef<{select:(i:number|null)=>void}|null>(null);const [selected,setSelected]=useState<number|null>(null);const [ready,setReady]=useState(false);const [error,setError]=useState(false);const choose=useRef((i:number|null)=>{});choose.current=(i)=>{setSelected(i);controller.current?.select(i)};const area=areas[selected??0];
useEffect(()=>{let stopped=false;let map:Leaflet.Map|undefined;let resize:ResizeObserver|undefined;let started=false;const el=host.current!;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!started){started=true;void boot()}},{rootMargin:'200px'});observer.observe(el);async function boot(){try{const [L,data]=await Promise.all([import('leaflet'),fetch('/assets/maps/valley-boundaries.geojson').then(r=>{if(!r.ok)throw Error('Boundary data');return r.json() as Promise<FeatureCollection<Geometry,Props>>})]);if(stopped)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;map=L.map(el,{scrollWheelZoom:false,zoomControl:false,attributionControl:true,minZoom:7,maxZoom:16,zoomSnap:.25});const bounds=L.latLngBounds([[32.98,-112.88],[33.93,-111.4]]);map.fitBounds(bounds,{padding:[10,10]});L.control.zoom({position:'bottomright'}).addTo(map);map.attributionControl.setPrefix(false);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
const layers=new Map<number,Leaflet.GeoJSON>();const markers=new Map<number,Leaflet.Marker>();data.features.forEach((feature:Feature<Geometry,Props>)=>{const name=feature.properties?.BASENAME||feature.properties?.NAME;const index=areas.findIndex(a=>a.name===name);if(index<0)return;const layer=L.geoJSON(feature,{style:{color:'#398dbd',weight:1,fillColor:'#069ee9',fillOpacity:.035},onEachFeature:(_,l)=>{l.on('click',()=>choose.current(index));l.on('mouseover',()=>{if(selected!==index)(l as Leaflet.Path).setStyle({weight:2,fillOpacity:.12})});l.on('mouseout',()=>controller.current?.select(selectedRef.current))}}).addTo(map!);layers.set(index,layer)});
areas.forEach((a,i)=>{const marker=L.marker([a.lat,a.lng],{icon:L.divIcon({className:'valley-city-pin',html:'<span class="city-pin-core"></span><span class="city-pin-label">'+a.name+'</span>',iconSize:[24,24],iconAnchor:[12,12]}),title:a.name,alt:'Zoom to '+a.name,keyboard:true}).on('click',()=>choose.current(i)).addTo(map!);markers.set(i,marker)});
let lastFocus:number|null=null;controller.current={select(i){layers.forEach((layer,index)=>layer.setStyle({color:index===i?'#48c5ff':'#398dbd',weight:index===i?2.5:1,fillOpacity:index===i?.27:.025,fillColor:'#009fea'}));markers.forEach((m,index)=>m.getElement()?.classList.toggle('selected',index===i));if(i===lastFocus)return;lastFocus=i;if(i===null){map!.flyToBounds(bounds,{padding:[10,10],duration:reduced?0:1.1,animate:!reduced});return}const layer=layers.get(i);layer?.bringToFront();if(layer)map!.flyToBounds(layer.getBounds(),{padding:[38,38],maxZoom:12.5,duration:reduced?0:1.1,animate:!reduced});else map!.flyTo([areas[i].lat,areas[i].lng],12,{duration:reduced?0:1.1,animate:!reduced})}};resize=new ResizeObserver(()=>map?.invalidateSize());resize.observe(el);setReady(true);controller.current.select(selectedRef.current)}catch{if(!stopped)setError(true)}}const selectedRef=selectionRef;return()=>{stopped=true;observer.disconnect();resize?.disconnect();controller.current=null;map?.remove()}},[]);
const selectionRef=useRef<number|null>(null);selectionRef.current=selected;
return <div className="geographic-explorer"><div className="map-frame"><div ref={host} className="geographic-map" role="region" aria-label="Interactive Phoenix Valley map. Select a city below to zoom and shade its boundary."/>{!ready&&<div className="map-loading">{error?'Map unavailable. Use the city links below.':'Opening the Valley map…'}</div>}<div className="map-toolbar"><span>{selected===null?'PHOENIX VALLEY':area.name.toUpperCase()+' / ARIZONA'}</span><button onClick={()=>choose.current(null)} disabled={!ready||selected===null}>View the whole Valley</button></div><div className="map-source">Boundaries: <a href="https://tigerweb.geo.census.gov/tigerweb/">U.S. Census</a> · <a href="https://maps.phoenix.gov/pub/rest/services/public/Villages/MapServer">City of Phoenix</a></div></div><div className="map-city-panel"><div className="city-selector" aria-label="Zoom to a service location">{areas.map((a,i)=><button key={a.slug} aria-pressed={selected===i} onClick={()=>choose.current(i)}>{a.name}</button>)}</div><div className="map-selected-info" aria-live="polite"><div><p className="eyebrow">{selected===null?'SELECT A LOCATION TO EXPLORE':'YOUR SELECTED LOCATION'}</p><h3>{selected===null?'Across the Valley.':area.name+', AZ'}</h3></div><div><p>{selected===null?'Find your city on the map or choose it above. We’ll bring its streets and boundary into focus.':area.intro}</p><a className="text-link" href={'/service-areas/'+area.slug+'-az/'}>{selected===null?'Explore our Laveen home base':'Plumbing in '+area.name}</a></div></div><p className="map-boundary-note">Shading identifies city boundaries and Laveen Village. Contact LPZ to confirm availability at your address.</p></div></div>
}

