import { Header,Footer } from '@/components/lpz-shell';
import { Breadcrumbs,metadataFor,JsonLd,origin } from '@/components/lpz-content';
import { ReadingProgress } from '@/components/journal-browser';
import { articles } from '@/lib/journal';
import { services,areas } from '@/lib/lpz-data';
import { notFound } from 'next/navigation';
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(x=>x.slug===slug);return a?metadataFor(a.title,a.intro,'/blog/'+slug+'/'):{};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(x=>x.slug===slug);if(!a)notFound();const service=services.find(s=>s.slug===a.service)!;const city=areas.find(c=>c.slug===a.city)!;return <><Header/><ReadingProgress/><main id="main"><section className="page-hero"><Breadcrumbs items={[{name:'Journal',path:'/blog/'},{name:a.title,path:'/blog/'+slug+'/'}]}/><p className="eyebrow">{a.category.toUpperCase()} / LPZ PLUMBING SOLUTIONS</p><h1>{a.title}</h1><p>{a.intro}</p></section><article className="section light"><div className="prose article-content"><nav className="article-toc" aria-label="Article contents"><strong>IN THIS GUIDE</strong>{a.sections.map(([title],i)=><a key={title} href={'#section-'+i}>{title}</a>)}</nav>{a.sections.map(([title,text],i)=><section key={title}><h2 id={'section-'+i}>{title}</h2><p>{text}</p></section>)}{a.source&&<p className="small-copy">Further reading: <a href={a.source[1]}>{a.source[0]}</a></p>}<h2>Plan the next step with LPZ.</h2><p>Explore <a href={'/services/'+service.slug+'/'}>{service.name.toLowerCase()}</a> or read about <a href={'/service-areas/'+city.slug+'-az/'}>plumbing service in {city.name}</a>.</p><a className="button" href="/schedule-service/">Request service</a></div></article><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.intro,author:{'@type':'Organization',name:'LPZ Plumbing Solutions'},mainEntityOfPage:origin+'/blog/'+slug+'/'}}/></main><Footer/></>}
